dist: xenial

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  global:
    - PIPENV_VERBOSITY=-1
  matrix:
    - DJANGO_VERSION=2.0
    - DJANGO_VERSION=2.1
    - DJANGO_VERSION=2.2

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pip install Django==${DJANGO_VERSION}

script:
  - pipenv run flake8
  - pipenv run pylint --rcfile=setup.cfg django_pyc test_project *.py
  - pipenv run bandit --ini setup.cfg --recursive --format screen .
  - pipenv run doc8 *.rst

  - pipenv run python manage.py test
  - pipenv run python setup.py sdist bdist_wheel

  - make -C docs html
